name: "Build Release"
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/checkout@v2, with: { fetch-depth: 0 } }
      - {
          uses: madhead/read-java-properties@latest,
          id: all,
          with: {
            file: gradle.properties,
            all: true
          }
        }
      - {
          name: "Set up JDK 17",
          uses: actions/setup-java@v2,
          with: { distribution: "adopt", java-version: "17" },
        }
      - {
          name: "Build with Gradle",
          id: build,
          run: "chmod +x gradlew && ./gradlew build publish",
        }
      - name: "maven publish"
        uses: appleboy/scp-action@master
        with:
          host: "wandhoven.ddns.net"
          username: ${{ secrets.SCP_MAVEN_USERNAME }}
          key: ${{ secrets.SCP_MAVENKEY }}
          source: "pub/"
          target: "/maven/B/html/maven/"
